spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/studentmanagementdb"
    #        You're username and password here to connect to DB
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: "true"
